export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Places',
    route: '/listings',
    description: 'Studios, spaces, and featured places.',
    contentType: 'listing',
    enabled: false,
  },
  {
    key: 'classified',
    label: 'Opportunities',
    route: '/classifieds',
    description: 'Calls, drops, and time-sensitive posts.',
    contentType: 'classified',
    enabled: false,
  },
  {
    key: 'article',
    label: 'Field Notes',
    route: '/articles',
    description: 'Essays, notes, and long-form context.',
    contentType: 'article',
    enabled: false,
  },
  {
  key: 'image',
  label: 'Image',
  route: '/image',
  description: 'Curated image content.',
  contentType: 'image',
  enabled: true,
},
  {
    key: 'profile',
    label: 'Profiles',
    route: '/profile',
    description: 'Artists, studios, and public identities.',
    contentType: 'profile',
    enabled: false,
  },
  {
    key: 'sbm',
    label: 'Bookmarks',
    route: '/sbm',
    description: 'Curated references, links, and saved resources.',
    contentType: 'social',
    enabled: false,
  },
  {
    key: 'comment',
    label: 'Commentary',
    route: '/blog',
    description: 'Responses and discussion layers.',
    contentType: 'article',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'PDF Library',
    route: '/pdf',
    description: 'Decks, documents, and downloadable files.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Studios',
    route: '/team',
    description: 'Studio and organization profiles.',
    contentType: 'profile',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listings',
  classified: '/classifieds',
  article: '/articles',
  image: '/images',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
