export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Business Listing',
    route: '/listing',
    description: 'Studios, spaces, and featured places.',
    contentType: 'listing',
    enabled: false,
  },
  {
    key: 'classified',
    label: 'Classified',
    route: '/classified',
    description: 'Calls, drops, and time-sensitive posts.',
    contentType: 'classified',
    enabled: false,
  },
  {
    key: 'article',
    label: 'Article',
    route: '/article',
    description: 'Essays, notes, and long-form context.',
    contentType: 'article',
    enabled: false,
  },
  {
  key: 'image',
  label: 'Image',
  route: '/image',
  description: 'Curated image content.',
  contentType: 'image',
  enabled: true,
},
  {
    key: 'profile',
    label: 'Profile',
    route: '/profile',
    description: 'Artists, studios, and public identities.',
    contentType: 'profile',
    enabled: false,
  },
  {
    key: 'sbm',
    label: 'Social Bookmarking',
    route: '/sbm',
    description: 'Curated references, links, and saved resources.',
    contentType: 'sbm',
    enabled: false,
  },
  {
    key: 'comment',
    label: 'Comment',
    route: '/blog',
    description: 'Responses and discussion layers.',
    contentType: 'comment',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'PDF',
    route: '/pdf',
    description: 'Decks, documents, and downloadable files.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Organization',
    route: '/team',
    description: 'Studio and organization profiles.',
    contentType: 'org',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listing',
  classified: '/classified',
  article: '/article',
  image: '/image',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
